# Generated by Django 5.1.3 on 2024-11-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0002_books_books_to_be_bought_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_to_be_bought',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
