# Generated by Django 5.1.3 on 2024-11-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_management", "0003_alter_books_to_be_bought_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="books_to_be_bought",
            name="status",
            field=models.CharField(
                choices=[("approved", "approved"), ("pending", "pending")],
                default="approved",
                max_length=40,
            ),
        ),
    ]
