# Generated by Django 5.1.3 on 2024-11-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("9:00-10:00", "9:00-10:00"),
                            ("10:00-11:00", "10:00-11:00"),
                            ("11:00-12:00", "11:00-12:00"),
                            ("12:00-1:00", "12:00-1:00"),
                            ("2:00-3:00", "2:00-3:00"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("Maths", "Maths"),
                            ("Data Structures", "Data Structures"),
                            ("Web Technology", "Web Technology"),
                            ("Automata Theory", "Automata Theory"),
                            ("Digital Design", "Digital Design"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "unique_together": {("day", "time")},
            },
        ),
    ]
