# Generated by Django 5.1.3 on 2024-11-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParkingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.IntegerField()),
                ("sensor_location", models.CharField(max_length=300)),
                ("parking_status", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
